#!/usr/bin/env php

<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use LockFiles\Commands\CompareLockFiles;

$app = new Application;
$app->add(new CompareLockFiles);
$app->run();